name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fmt
      run: cargo fmt --all

  clippy_and_build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: sudo apt update && sudo apt install -y --no-install-recommends libasound2-dev pkg-config
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test --verbose

